const industries=['餐饮零售','智能制造','企业服务','健康医疗','教育培训','新能源','文娱消费','农业科技','跨境电商','本地生活'];
const names=['社区精品咖啡店','预制菜社区仓','工业视觉质检 SaaS','小型协作机器人租赁','中小企业财税自动化','AI 客服外呼平台','慢病管理线上诊所','银发康复护理站','AI 职业技能训练营','少儿科学实验空间','园区光储充一体站','家庭节能改造服务','沉浸式剧本娱乐馆','独立运动潮牌','城市垂直农场','农产品产地直播供应链','宠物用品 DTC 出海','户外装备小批量品牌','社区家政标准化平台','即时维修到家网络'];
const summaries=['面向办公社区和居住区的高复购咖啡门店，核心变量是坪效、复购和外卖占比。','用中央厨房和前置仓覆盖家庭晚餐场景，依赖供应链、损耗控制与社区获客。','为工厂提供视觉识别质检系统，销售周期长但续费和项目复制价值高。','面向中小工厂提供按月租用的协作机器人工作站，降低客户一次性投入。','帮助小微企业自动开票、记账、报税和经营看板，靠低客单价规模化续费。','为销售和售后团队提供智能外呼、质检与工单流转，受合规和转化率影响大。','围绕糖尿病、高血压等慢病做医患随访、用药提醒和健康商品转化。','在社区内提供康复训练、居家护理和家属管理服务，重在信任和服务标准化。','面向职场人提供 AI 办公、数据分析和自动化课程，收入高但内容迭代快。','线下小班科学实验和赛事辅导，靠安全、师资、续班率和本地口碑增长。','为产业园提供光伏、储能和充电服务，资本开支大，收益受利用率和电价政策影响。','给家庭提供热泵、门窗、智能用电和节能评估套餐，适合渠道驱动。','结合剧本杀、互动演出和会员社交，内容更新和复购体验决定天花板。','面向跑步、骑行、飞盘等圈层做功能服饰和内容社区，库存管理是生死线。','用水培和环境控制生产叶菜、香草和微型菜，靠稳定品质和渠道溢价盈利。','链接产地、主播和城市消费者，核心是选品、履约和复购。','通过独立站和平台销售宠物智能用品、玩具和消耗品，受广告成本和复购影响大。','围绕露营、徒步和车载旅行做轻量化装备，适合小批量快速迭代。','提供保洁、收纳、老人陪护和维修服务，服务质量和调度效率决定复购。','覆盖手机、家电、电脑和智能门锁维修，靠技师网络、配件供应和价格透明建立信任。'];
const caps=['45-90 万','80-180 万','180-420 万','260-650 万','120-260 万','160-360 万','220-500 万','90-210 万','70-180 万','80-200 万','500-1500 万','100-240 万','120-300 万','150-380 万','300-900 万','60-160 万','160-420 万','120-300 万','80-220 万','90-240 万'];
const risks=['中','中高','中','高','中','中高','高','中','中','中','高','中','中高','中高','高','中','中高','中','中','中']; const bases=[54,49,57,52,61,56,50,55,59,53,51,58,47,50,46,56,55,52,60,57];
const projects=names.map((name,i)=>({id:i+1,name,industry:industries[Math.floor(i/2)],summary:summaries[i],base:bases[i],capital:caps[i],payback:i%3==0?'14-24 个月':i%3==1?'18-30 个月':'24-42 个月',margin:i%4==0?'58%-78%':i%4==1?'32%-55%':i%4==2?'42%-66%':'25%-48%',risk:risks[i],case:'参考同类成熟公司和区域创业样本：增长曲线通常由需求强度、履约稳定、现金流安全和获客效率共同决定。',model:{revenue:'核心产品销售、会员或订阅、增值服务、企业合作',cost:'人力、获客、供应链、场地或云服务、合规与售后',moat:'数据沉淀、品牌信任、渠道网络、运营 SOP'}}));
const params=[
{key:'capital',name:'资金投入',unit:'万元',min:10,max:1000,base:100,step:10,weight:.13,affects:'现金流安全、试错次数、获客投放和设备采购能力',guide:[['1-2分','只够启动，现金流少于 3 个月，没有试错预算。'],['3-4分','能完成首批采购/装修/研发，但只能验证一个渠道。'],['5-6分','能支撑 6-9 个月运营，允许 2-3 次小规模试错。'],['7-8分','能覆盖 9-15 个月现金流，有稳定获客和关键岗位预算。'],['9-10分','有 15 个月以上安全期，可承受扩张、库存和政策波动。']]},
{key:'team',name:'核心团队能力',unit:'分',min:1,max:10,base:6,step:1,weight:.14,affects:'执行速度、招聘质量、战略判断和危机处理',guide:[['1-2分','创始人无相关行业经验，角色缺失，重大事项靠临时摸索。'],['3-4分','有单点经验，但缺少销售、产品、财务或运营中的关键角色。'],['5-6分','核心岗位基本齐，做过相近项目，能按周复盘调整。'],['7-8分','团队有完整行业经验，能招聘管理，关键指标有人负责。'],['9-10分','团队曾做成同类业务，有资源、管理体系和融资/并购经验。']]},
{key:'market',name:'市场需求强度',unit:'分',min:1,max:10,base:6,step:1,weight:.12,affects:'自然增长、价格弹性、销售转化和增长上限',guide:[['1-2分','需求是假设，目标客户不愿付费或频次极低。'],['3-4分','少量客户感兴趣，但痛点不急，替代方案很多。'],['5-6分','有稳定需求，能拿到付费样本，但增长还依赖主动销售。'],['7-8分','需求明确且复购明显，客户会主动搜索或转介绍。'],['9-10分','需求高速增长，供给不足，客户愿意预付或排队。']]},
{key:'differentiation',name:'差异化程度',unit:'分',min:1,max:10,base:5,step:1,weight:.1,affects:'获客成本、议价能力、复购理由和品牌记忆',guide:[['1-2分','产品和竞品几乎一样，只能靠低价竞争。'],['3-4分','有包装或服务差异，但客户感知不强。'],['5-6分','有 1-2 个明确卖点，客户能说出选择理由。'],['7-8分','卖点难复制，能支撑溢价或更高转化率。'],['9-10分','形成品类心智、专利/数据/供应链优势或强品牌壁垒。']]},
{key:'pricing',name:'定价竞争力',unit:'分',min:1,max:10,base:6,step:1,weight:.08,affects:'毛利率、转化率、回本速度和客户质量',guide:[['1-2分','价格高但价值不清，或低价导致毛利不可持续。'],['3-4分','能成交，但毛利、回本或客户质量至少一项明显失衡。'],['5-6分','价格与价值匹配，毛利能覆盖基础运营。'],['7-8分','有套餐、分层或订阅设计，兼顾转化和毛利。'],['9-10分','具备强议价权，客户愿意预付，高毛利仍能保持转化。']]},
{key:'marketing',name:'营销效率',unit:'分',min:1,max:10,base:5,step:1,weight:.1,affects:'线索成本、品牌声量、首单转化和渠道扩张',guide:[['1-2分','没有稳定获客渠道，主要靠熟人和偶然曝光。'],['3-4分','有投放或内容，但成本高、转化不稳定。'],['5-6分','至少一个渠道可持续获客，能计算 CAC 和转化率。'],['7-8分','多个渠道可复制，私域/转介绍开始贡献增长。'],['9-10分','获客飞轮形成，内容、渠道、销售漏斗都可规模化。']]},
{key:'operations',name:'运营成熟度',unit:'分',min:1,max:10,base:6,step:1,weight:.11,affects:'履约稳定、损耗率、客户体验和组织效率',guide:[['1-2分','流程靠个人经验，交付质量波动大，客诉难追踪。'],['3-4分','有基础流程，但高峰期、缺人或异常订单容易失控。'],['5-6分','有 SOP、排班/库存/项目表，主要指标能周度复盘。'],['7-8分','流程数字化，质量稳定，单店/单团队模型能复制。'],['9-10分','形成标准化运营系统，跨区域或多团队仍能保持效率。']]},
{key:'supply',name:'供应链稳定性',unit:'分',min:1,max:10,base:6,step:1,weight:.08,affects:'成本波动、交付周期、库存风险和质量一致性',guide:[['1-2分','依赖单一供应商，价格和交期不可控。'],['3-4分','有备选供应商，但质量、账期或库存压力较大。'],['5-6分','核心物料/服务稳定，能控制损耗和交期。'],['7-8分','有议价能力、备份体系和质量验收标准。'],['9-10分','供应链深度绑定，可定制、低成本、快速响应。']]},
{key:'tech',name:'技术/数据能力',unit:'分',min:1,max:10,base:5,step:1,weight:.07,affects:'自动化程度、决策质量、产品迭代和规模化复制',guide:[['1-2分','主要靠手工记录，数据缺失，决策凭感觉。'],['3-4分','有基础表格或工具，但数据不完整、不及时。'],['5-6分','能追踪核心指标，支持定价、库存、投放或产品迭代。'],['7-8分','关键流程自动化，数据能指导精细化运营。'],['9-10分','技术成为核心壁垒，算法、系统或数据资产可复制变现。']]},
{key:'compliance',name:'合规安全',unit:'分',min:1,max:10,base:7,step:1,weight:.07,affects:'牌照风险、政策变化、客诉成本和长期经营资格',guide:[['1-2分','资质、合同、税务、数据或安全存在明显红线。'],['3-4分','知道主要要求，但证照、合同或风控还不完整。'],['5-6分','基础合规齐全，能处理常见投诉和检查。'],['7-8分','合规流程固定，关键岗位有记录、培训和责任人。'],['9-10分','合规成为优势，可通过审计、保险、牌照或大客户准入。']]}];
const state={industry:industries[0],projectId:1,values:{}}; const $=id=>document.getElementById(id); function reset(){state.values={};params.forEach(p=>state.values[p.key]=p.base)} function project(){return projects.find(p=>p.id===state.projectId)} function moneyScore(v){return Math.min(10,Math.sqrt(v/100)*6)} function normalizedValue(key,value){return key==='capital'?moneyScore(value):value} function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function scoreFor(values){let p=project(),w=0;params.forEach(x=>{w+=normalizedValue(x.key,values[x.key])*x.weight});let s=p.base+(w-6)*7;if(values.compliance<4)s-=8;if(values.operations<4)s-=5;if(values.capital<40)s-=6;if((values.team+values.operations+values.market)/3>7.5)s+=5;return Math.round(clamp(s,8,92))} function score(){return scoreFor(state.values)}
function renderIndustry(){ $('industrySelect').innerHTML=industries.map(i=>'<option '+(i===state.industry?'selected':'')+'>'+i+'</option>').join(''); renderProjects()} function renderProjects(){let list=projects.filter(p=>p.industry===state.industry); if(!list.some(p=>p.id===state.projectId))state.projectId=list[0].id; $('projectList').innerHTML=list.map(p=>'<button class="project-btn '+(p.id===state.projectId?'active':'')+'" data-id="'+p.id+'"><strong>'+p.name+'</strong><span>'+p.summary+'</span></button>').join(''); document.querySelectorAll('.project-btn').forEach(b=>b.onclick=()=>{state.projectId=Number(b.dataset.id);reset();renderAll()})}
function renderControls(){ $('controls').innerHTML=params.map(p=>{let guide=p.guide.map(g=>'<div class="rubric-row"><strong>'+g[0]+'</strong><span>'+g[1]+'</span></div>').join(''); return '<div class="control"><div class="control-top"><span>'+p.name+'</span><span class="value-pill">'+state.values[p.key]+p.unit+'</span></div><input type="range" min="'+p.min+'" max="'+p.max+'" step="'+p.step+'" value="'+state.values[p.key]+'" data-key="'+p.key+'"><div class="control-foot"><span>影响：'+p.affects+'</span><span>权重：'+Math.round(p.weight*100)+'%</span></div><div class="rubric">'+guide+'</div></div>'}).join(''); document.querySelectorAll('input[type=range]').forEach(r=>r.oninput=e=>{state.values[e.target.dataset.key]=Number(e.target.value);renderControls();renderResults()})}
function renderProject(){let p=project();$('projectIndustry').textContent=p.industry;$('projectName').textContent=p.name;$('projectSummary').textContent=p.summary;$('capitalNeed').textContent=p.capital;$('paybackTime').textContent=p.payback;$('grossMargin').textContent=p.margin;$('riskLevel').textContent=p.risk}
function renderResults(){let p=project(),s=score();$('successRate').textContent=s+'%';$('meterFill').style.width=s+'%';$('confidenceLabel').textContent=s>=80?'接近 80% 目标':s>=70?'高潜力方案':s>=50?'可验证方案':'需重构方案';let monthly=Math.round(state.values.capital*(state.values.operations+state.values.marketing)/18), burn=Math.round(state.values.capital/(state.values.team+state.values.operations)*1.8), cac=Math.max(18,Math.round(260-(state.values.marketing*16+state.values.differentiation*9))), ltv=Math.round(state.values.pricing*90+state.values.operations*70+state.values.market*60);$('resultStack').innerHTML=[['预计月收入',monthly+' 万元'],['现金流安全期',burn+' 个月'],['获客成本指数',cac],['客户生命周期价值',ltv],['建议验证周期',s>=65?'90 天内扩大样本':'30-60 天做小规模验证']].map(x=>'<div class="result"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>').join('');renderTarget(s);renderDetails(s)}
function computeTarget(target){let values=Object.assign({},state.values), start=scoreFor(values), rows=[];let guard=0;while(scoreFor(values)<target&&guard<200){guard++;let best=null;params.forEach(p=>{let next=Object.assign({},values); if(next[p.key]>=p.max)return; next[p.key]=Math.min(p.max,next[p.key]+p.step); let gain=scoreFor(next)-scoreFor(values); let cost=p.key==='capital'?p.step/100:p.step; let efficiency=gain/(cost||1); if(gain>0&&(!best||efficiency>best.efficiency)){best={p,next,gain,efficiency}}}); if(!best)break; values=best.next;} params.forEach(p=>{if(values[p.key]>state.values[p.key])rows.push({name:p.name,now:state.values[p.key]+p.unit,target:values[p.key]+p.unit,why:p.affects})}); return {start,final:scoreFor(values),values,rows}}
function renderTarget(currentScore){let t=computeTarget(80);$('targetStatus').textContent=currentScore>=80?'当前已达到':'目标 80%'; if(currentScore>=80){$('targetPlan').innerHTML='<div class="target-grid"><div class="target-card"><span>当前状态</span><strong>已经达到 80% 以上</strong></div><div class="target-card"><span>建议</span><strong>保持参数，不要盲目加杠杆</strong></div></div>';return} let rowHtml=t.rows.length?t.rows.map(r=>'<div class="target-row"><div>'+r.name+'</div><div>'+r.now+'</div><div class="need">'+r.target+'</div><div>'+r.why+'</div></div>').join(''):'<div class="target-row"><div>暂无</div><div>-</div><div>-</div><div>当前模型无法通过单项增量继续提升，请换项目或重构商业模型。</div></div>'; $('targetPlan').innerHTML='<div class="target-grid"><div class="target-card"><span>当前成功率</span><strong>'+currentScore+'%</strong></div><div class="target-card"><span>按反推可达到</span><strong>'+t.final+'%</strong></div></div><div class="target-table"><div class="target-row"><div>参数</div><div>当前</div><div>建议目标</div><div>为什么要补</div></div>'+rowHtml+'</div>'}
function renderDetails(s){let p=project();let weak=params.filter(x=>normalizedValue(x.key,state.values[x.key])<5.5);let strong=params.filter(x=>normalizedValue(x.key,state.values[x.key])>=7.5);$('planList').innerHTML=['先用 '+state.values.capital+' 万元预算完成 MVP、首店或首批客户模型，验证真实付费、复购和交付成本。','把 '+(strong[0]?strong[0].name:'团队能力')+' 作为增长杠杆，优先放大已经有优势的环节。','针对 '+(weak[0]?weak[0].name:'合规安全')+' 设置止损线，连续两个周期不达标就收缩投入。','建立周度经营看板：收入、毛利、现金流、获客成本、复购率、客诉率必须同步跟踪。'].map(i=>'<li>'+i+'</li>').join('');$('businessModel').innerHTML='<div class="kv"><strong>收入来源</strong><span>'+p.model.revenue+'</span></div><div class="kv"><strong>成本结构</strong><span>'+p.model.cost+'</span></div><div class="kv"><strong>护城河</strong><span>'+p.model.moat+'</span></div><div class="tag-row"><span class="tag">成功率 '+s+'%</span><span class="tag">行业 '+p.industry+'</span><span class="tag">风险 '+p.risk+'</span></div>';$('caseStudy').innerHTML='<div class="note">'+p.case+'</div><div class="note">本模拟不是财务承诺，而是把行业曲线、经营参数和常见失败因素转成可比较的推演分数。</div>';$('impactNotes').innerHTML=params.map(x=>'<div class="note"><strong>'+x.name+'</strong>：'+x.affects+'。评分请参考左侧该参数下方的 1-10 分标准。</div>').join('')}
function renderAll(){renderProjects();renderProject();renderControls();renderResults()} $('industrySelect').onchange=e=>{state.industry=e.target.value;renderAll()};$('resetBtn').onclick=()=>{reset();renderAll()};reset();renderIndustry();renderAll();